//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.14 at 04:36:17 PM CEST 
//


package pl.prxsoft.sample.eai.telco.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contractType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ratePlan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billingDay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loyaltyLength" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terminal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terminalPriceNetto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="monthlyCommitmentNetto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="services" type="{}servicesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contractType", propOrder = {
    "msisdn",
    "ratePlan",
    "startDate",
    "billingDay",
    "loyaltyLength",
    "terminal",
    "terminalPriceNetto",
    "monthlyCommitmentNetto",
    "services"
})
public class ContractType {

    @XmlElement(required = true)
    protected String msisdn;
    @XmlElement(required = true)
    protected String ratePlan;
    @XmlElement(required = true)
    protected String startDate;
    @XmlElement(required = true)
    protected String billingDay;
    @XmlElement(required = true)
    protected String loyaltyLength;
    @XmlElement(required = true)
    protected String terminal;
    @XmlElement(required = true)
    protected String terminalPriceNetto;
    @XmlElement(required = true)
    protected String monthlyCommitmentNetto;
    @XmlElement(required = true)
    protected ServicesType services;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the ratePlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatePlan() {
        return ratePlan;
    }

    /**
     * Sets the value of the ratePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatePlan(String value) {
        this.ratePlan = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the billingDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingDay() {
        return billingDay;
    }

    /**
     * Sets the value of the billingDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingDay(String value) {
        this.billingDay = value;
    }

    /**
     * Gets the value of the loyaltyLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoyaltyLength() {
        return loyaltyLength;
    }

    /**
     * Sets the value of the loyaltyLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoyaltyLength(String value) {
        this.loyaltyLength = value;
    }

    /**
     * Gets the value of the terminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminal() {
        return terminal;
    }

    /**
     * Sets the value of the terminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminal(String value) {
        this.terminal = value;
    }

    /**
     * Gets the value of the terminalPriceNetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalPriceNetto() {
        return terminalPriceNetto;
    }

    /**
     * Sets the value of the terminalPriceNetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalPriceNetto(String value) {
        this.terminalPriceNetto = value;
    }

    /**
     * Gets the value of the monthlyCommitmentNetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthlyCommitmentNetto() {
        return monthlyCommitmentNetto;
    }

    /**
     * Sets the value of the monthlyCommitmentNetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthlyCommitmentNetto(String value) {
        this.monthlyCommitmentNetto = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesType }
     *     
     */
    public ServicesType getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesType }
     *     
     */
    public void setServices(ServicesType value) {
        this.services = value;
    }

}
