//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.14 at 04:36:17 PM CEST 
//


package pl.prxsoft.sample.eai.telco.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.prxsoft.sample.eai.telco.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Order_QNAME = new QName("", "order");
    private final static QName _ServiceTypeServiceParameter_QNAME = new QName("", "serviceParameter");
    private final static QName _ServiceTypeServicePrice_QNAME = new QName("", "servicePrice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.prxsoft.sample.eai.telco.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BillingAddressType }
     * 
     */
    public BillingAddressType createBillingAddressType() {
        return new BillingAddressType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link ServiceParameterType }
     * 
     */
    public ServiceParameterType createServiceParameterType() {
        return new ServiceParameterType();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link IssueContextType }
     * 
     */
    public IssueContextType createIssueContextType() {
        return new IssueContextType();
    }

    /**
     * Create an instance of {@link ServicePriceType }
     * 
     */
    public ServicePriceType createServicePriceType() {
        return new ServicePriceType();
    }

    /**
     * Create an instance of {@link ServicesType }
     * 
     */
    public ServicesType createServicesType() {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link ContractType }
     * 
     */
    public ContractType createContractType() {
        return new ContractType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link ContractsType }
     * 
     */
    public ContractsType createContractsType() {
        return new ContractsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "order")
    public JAXBElement<OrderType> createOrder(OrderType value) {
        return new JAXBElement<OrderType>(_Order_QNAME, OrderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceParameter", scope = ServiceType.class)
    public JAXBElement<ServiceParameterType> createServiceTypeServiceParameter(ServiceParameterType value) {
        return new JAXBElement<ServiceParameterType>(_ServiceTypeServiceParameter_QNAME, ServiceParameterType.class, ServiceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServicePriceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "servicePrice", scope = ServiceType.class)
    public JAXBElement<ServicePriceType> createServiceTypeServicePrice(ServicePriceType value) {
        return new JAXBElement<ServicePriceType>(_ServiceTypeServicePrice_QNAME, ServicePriceType.class, ServiceType.class, value);
    }

}
