//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.14 at 04:36:17 PM CEST 
//


package pl.prxsoft.sample.eai.telco.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account" type="{}accountType"/>
 *         &lt;element name="accountAction" type="{}accountAndContractActionEnum"/>
 *         &lt;element name="customer" type="{}customerType"/>
 *         &lt;element name="customerAction" type="{}accountAndContractActionEnum"/>
 *         &lt;element name="contracts" type="{}contractsType"/>
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issueContext" type="{}issueContextType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderType", propOrder = {
    "account",
    "accountAction",
    "customer",
    "customerAction",
    "contracts",
    "action",
    "issueContext"
})
public class OrderType {

    @XmlElement(required = true)
    protected AccountType account;
    @XmlElement(required = true)
    protected AccountAndContractActionEnum accountAction;
    @XmlElement(required = true)
    protected CustomerType customer;
    @XmlElement(required = true)
    protected AccountAndContractActionEnum customerAction;
    @XmlElement(required = true)
    protected ContractsType contracts;
    @XmlElement(required = true)
    protected String action;
    @XmlElement(required = true)
    protected IssueContextType issueContext;

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link AccountType }
     *     
     */
    public AccountType getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountType }
     *     
     */
    public void setAccount(AccountType value) {
        this.account = value;
    }

    /**
     * Gets the value of the accountAction property.
     * 
     * @return
     *     possible object is
     *     {@link AccountAndContractActionEnum }
     *     
     */
    public AccountAndContractActionEnum getAccountAction() {
        return accountAction;
    }

    /**
     * Sets the value of the accountAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountAndContractActionEnum }
     *     
     */
    public void setAccountAction(AccountAndContractActionEnum value) {
        this.accountAction = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     */
    public void setCustomer(CustomerType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the customerAction property.
     * 
     * @return
     *     possible object is
     *     {@link AccountAndContractActionEnum }
     *     
     */
    public AccountAndContractActionEnum getCustomerAction() {
        return customerAction;
    }

    /**
     * Sets the value of the customerAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountAndContractActionEnum }
     *     
     */
    public void setCustomerAction(AccountAndContractActionEnum value) {
        this.customerAction = value;
    }

    /**
     * Gets the value of the contracts property.
     * 
     * @return
     *     possible object is
     *     {@link ContractsType }
     *     
     */
    public ContractsType getContracts() {
        return contracts;
    }

    /**
     * Sets the value of the contracts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractsType }
     *     
     */
    public void setContracts(ContractsType value) {
        this.contracts = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the issueContext property.
     * 
     * @return
     *     possible object is
     *     {@link IssueContextType }
     *     
     */
    public IssueContextType getIssueContext() {
        return issueContext;
    }

    /**
     * Sets the value of the issueContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueContextType }
     *     
     */
    public void setIssueContext(IssueContextType value) {
        this.issueContext = value;
    }

}
